name: ActionUpdate # GitHub Actionsにつける名前。任意で良い。

on:
  schedule:
    - cron: '49 * * * *' # cronで定期実行

jobs:
  build:
    runs-on: ubuntu-latest # 最新のubuntu環境で下記のジョブを実行
    steps:
      - uses: actions/checkout@v2 # おまじない

      - name: Setup python # ワークフローのセクションごとに設定する名前。特に設定する必要はないが、どこでエラーが起きているかを把握する為にも設定しておいた方が良い。
        uses: actions/setup-python@v2 # Pythonのセットアップ
        with:
          python-version: "3.9.5" # Pythonのバージョン指定

      - name: Run ActionScript.py # Pythonファイルの実行
        run: |
          python ActionScript.py

      - name: Commit and Push # 実行した結果をプッシュして変更をレポジトリに反映
        run: |
          git config user.name "antiapplemicrosoftuser"
          git config user.email "antiapp1emicros0ftuser@outlook.jp"
          git add .
          git commit -m "$(date) Updated."
          git pull
          git push